src/submission/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views


urlpatterns = [
    url(r'^download/(?P<submission_id>[0-9]+)$', views.download, name='download'),
    url(r'^create/', views.SubmissionCreate.as_view(), name='SubmissionCreateView'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.SubmissionUpdate.as_view(), name='SubmissionUpdateView'),
    url(r'^delete/(?P<pk>[0-9]+)$', views.SubmissionDelete.as_view(), name='SubmissionDeleteView'),
    url(r'^', views.SubmissionList.as_view(), name='SubmissionListView'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.SubmissionDetail.as_view(), name='SubmissionDetailView'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/submission/models.py
from django.db import models
from educator.models import Educator
from django.utils import timezone

import os

from django.conf import settings

from degree.models import Degree

from django.dispatch import receiver


from submission.analysis import main as submission_analysis


def get_path(instance, filename):
    return '{}/{}/{}'.format(instance.degree.code, instance.id, filename)


class Submission(models.Model):
    STATUS_ONGOING = 0
    STATUS_FINISHED = 1
    STATUS_FAIL = 2

    STATUS_CHOICES = (
        (STATUS_ONGOING, 'Em andamento'),
        (STATUS_FINISHED, 'Terminado'),
    )

    ANALYSIS_STATUS_CHOICES = (
        (STATUS_ONGOING, 'Executando'),
        (STATUS_FINISHED, 'Terminado'),
        (STATUS_FAIL, 'Falha'),
    )
    author = models.ForeignKey(Educator)

    csv_data_file = models.FileField(upload_to=get_path)

    degree = models.ForeignKey(Degree, related_name='submissions')
    timestamp = models.DateTimeField(default=timezone.now)
    last = models.BooleanField(default=True)
    processed = models.BooleanField(default=False)
    process_time = models.IntegerField(null=True)
    analysis_status = models.IntegerField(
            default=0,
            choices=ANALYSIS_STATUS_CHOICES
            )
    last_error = models.CharField(default="", max_length=4096)
    relative_year = models.IntegerField(null=True)
    relative_semester = models.IntegerField(null=True)
    semester_status = models.IntegerField(null=True, choices=STATUS_CHOICES)
    done_in = models.DateTimeField(null=True)

    class Meta:
        permissions = (
            # ('view_submission', 'Visualizar Relatórios'),
            ('view_course', 'Visualizar disciplinas'),
            ('view_student', 'Visualizar alunos'),
            ('view_degree', 'Visualizar curso'),
            ('view_admission', 'Visualizar turma ingresso'),
            ('view_cepe9615', 'Visualizar  cepe9615')
            )

    def save(self, *args, **kwargs):
        """
        Sobrescrita do metodo save.
        É necesário rescrever o metodo save, para poder obter o id da instancia
        enquanto o modelo ainda não foi salvo no banco de dados.

        """
        if self.id is None:
            csv_data_file = self.csv_data_file
            self.csv_data_file = None
            super(Submission, self).save(*args, **kwargs)
            self.csv_data_file = csv_data_file
            # kwargs.pop('force_insert')
        super(Submission, self).save(*args, **kwargs)


    def path(self):
        return os.path.join(settings.MEDIA_ROOT, self.degree.code, str(self.id))

    def zip_path(self):
        return os.path.join(self.path(), "{}_data.zip".format(self.degree.name))

    def __str__(self):
        return 'Submission (from: {}, to: {}, on: {})'.format(self.author.user.first_name,
                                                              self.degree.name,
                                                              self.timestamp)
    
    def download_allowed(self, user):
        return (user == self.author.user) or user.is_superuser
    
    def set_executing(self):
        self.processed = False
        self.process_time = None
        self.done_in = timezone.now()
        self.analysis_status = 0
        self.save()

    def set_done(self, time):
        self.processed = True
        self.process_time = time
        self.done_in = timezone.now()
        self.analysis_status = 1
        self.save()

    def set_fail(self,time, error_message):
        self.processed = False
        self.process_time = time
        self.done_in = timezone.now()
        self.analysis_status = 2
        self.last_error = error_message
        self.save()

src/submission/templates/submission_create.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="alert alert-light" role="alert">
	Selecione as planilhas adquiridas a partir dos relatórios providos pelo
	sistema SIE.<br><br>


	Ao clicar no botão "Enviar relatório", você entrará em um estado de espera,
	onde a página ficará ociosa em um status de carregamento.<br><br>

	Caso o processamento dos dados execute em pouco tempo, você receberá uma mensagem de confirmação.<br><br>

	É possível, caso o processamento demore muito tempo, que a página perca o
	status de ociosa, perdendo a indicação de que o processamento está sendo realizado.
	Caso isso aconteça, verifique a página de <a href="{% url 'submission:SubmissionListView' %}">Gerenciamento de relatórios</a>
	e visualize o status do processamento do upload dos relatórios (planilhas do SIE),
	que pode ser "Terminado", "Executando" ou "Falha".<br><br>
    
    Para entender o fluxo completo dos dados, recomendamos acessar o <a href="https://petcomputacaoufpr.github.io/adega/web_pages/index.html#upload">guia de uso geral do ADEGA</a>.
    <br><br>

    Certifique-se que os dados enviados estão em uma planilha de formato <i>.csv</i>.<br>
    Essa planilha deve seguir o modelo gerado pelo nosso <a href="https://gitlab.c3sl.ufpr.br/adega/conversor-de-dados-adega/tree/master">conversor de dados</a>, disponível em um repositório aberto.
</div>


<div class="formBox form-group ">
    <form id="form_sub" method="post" accept-charset="utf-8" enctype="multipart/form-data">
		{% csrf_token %}

        <!-- Uploads files -->
        <div class="form-row">
            <div class="col-lg-5 col-md-5 col-sm-4">
                <label for="csv_data_file" type="file"
                    class="custom-file-label" id="csv_data_file_label">Dados (formato .csv)</label>
                <input type="file" name="csv_data_file"
                class="custom-file-input" id="csv_data_file"/>
            </div>

        </div>

        <!-- Integer field -->
        <div class="form-row">
            <div class="col-lg-5 col-md-5">
                <label for="relative_year">Ano do relatório</label>
                <input type="number" class="form-control" name="relative_year" id="relative_year"
                                                        value="{{form.relative_year.field.initial}}" />
            </div>

            <div class="col-lg-5 col-md-5 offset-lg-1 offset-md-1">
                <label for="relative_semester">Semestre do relatório</label>
                <input type="number" class="form-control" name="relative_semester" id="relative_semester"
                                                        value="{{form.relative_semester.field.initial}}" />
            </div>
        </div>

        <!-- Select field -->
        <div class="form-row">
            <div class="col-lg-5 col-md-5">
               <label>Selecione o status do semestre</label>
               <select name="semester_status" class="browser-default custom-select" id="semester_status">
                   {% for choice in form.semester_status.field.choices %}
                   <option value="{{choice.0}}">{{choice.1}}</option>
                   {% endfor %}
               </select>
            </div>


            <div class="col-lg-5 col-md-5 offset-lg-1 offset-md-1">
               <label>Selecione o curso de graduação</label>
               <select name="degree" class="browser-default custom-select" id="degree">
                    {% for degree in degree_options %}
                    <option value="{{degree.id}}">{{degree.name}}</option>
                    {% endfor %}
               </select>
            </div>

        </div>
        <br>
        <!-- Permissions -->
        <div class="row">
            <table class="table table-striped" id="ptable" >
              <thead >
                  <tr>
                    <th rowspan="3">Usuário</th>
                    <th colspan="5">Permissões</th>
                  </tr>
                  <tr>
                    {% for permission in permissions %}
                      <th scope="col"> {{permission}}</th>
                    {% endfor %}
                  </tr>
              </thead>
              <tbody>
                {% for user in users %}
                  <tr>
                    <th>{{user}}</th>
                    {% for permission in perms %}
                      <td>
                        <div class="form-check">
                          <input class="form-check-input position-static"
                                 type="checkbox"
                                 id="perm-{{user}}-{{permission}}"
                                 name="perm-{{user}}-{{permission}}"
                                 value=1 aria-label="...">
                        </div>
                      </td>
                    {% endfor %}
                  </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>

		<div class="row">
			<div class="col-lg-3 col-md-4 col-sm-4 offset-lg-2">
				<button id="submit_button" class="btn btn-success btn-block" type="submit">Enviar relatório</button>
			</div>
			<div class="col-lg-3 col-md-4 col-sm-4">
        <a class="btn btn-danger btn-block" style="text-decoration: none!important;" href="{% url 'submission:SubmissionListView' %}">Cancelar</a>
			</div>
    </div>
    <br>
    <div id="submit_progress" style="display:none">
      <div class="spinner-border" role="status">
        <span class="sr-only">Loading...</span>
      </div><br>
      Processando dados, por favor aguarde...<br>
      Ao final do processamento você será redirecionado para a página inicial.
    </div>
    </form>
</div>
{% endblock content %}

{% block js-foot %}
    <script src="{% static 'datatables/jquery.dataTables.min.js' %}">
        $('#ptable').dataTable({
            "bPaginate": true,
            "bInfo": false,
            "aaSorting": [[ 1, "desc" ]],
            "responsive": true
        });
    </script>

    <script>
        $( document ).ready(function() {
          $("#submit_progress").hide();
        });
        // Change the file input to add its name
        $('.custom-file-input').on('change',function(e){
            //get the file name
            // var fileName = $(this).val();
            var fileName = e.target.files[0].name;
            //replace the "Choose a file" label
            var newText = "<b>"+fileName+"</b>";
            $("#csv_data_file_label").html(newText);
        })

        $("#submit_button").click(function(e){
          $("#submit_progress").show();
        });
    </script>

{% endblock js-foot %}

src/submission/templates/submission_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
	<div class="col-sm-6">
		<h2>Relatórios enviados</h2>
	</div>
	<div class="col-offset-8">
		<a href="{% url 'submission:SubmissionCreateView' %}"> <button type="button" class="btn btn-primary">Upload de novos dados</button></a>
	</div>

</div>

<div class="alert alert-light" role="alert">
	Esta página contém os uploads de relatórios realizados por diferentes usuários
	que você possui acesso para gerenciar.<br><br>

	As linhas em vermelho indicam os relatórios (planilhas) que não puderam ser processados.
	Caso este problema aconteça, verifique novamente na etapa de que pode ser causado
	pela incompatibilidade das planilhas submetidas em
	<a href="{% url 'submission:SubmissionCreateView' %}">Upload de dados (relatório do SIE)</a>
	(colunas faltando, ordem errada do upload das planilhas de matrícula e histórico).<br><br>

	Também, ao realizar o upload verifique o Status do upload que, caso esteja em
	estado de processamento, terá coloração amarela na tabela a seguir.
</div>

<div class="row">
	<div class="table-responsive">
		<table id="submission_table" class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Identificador do upload do relatório</th>
					<th>Curso</th>
					<th>Autor</th>
					<th>Ano</th>
					<th>Semestre</th>
					<th>Status do processamento</th>
					<th>Data do upload</th>
					<th>Ações</th>
				</tr>
			</thead>
			<tbody>
				{% for sub in submission %}
						<tr>
							<td>{{sub.id}} </td>
							<td>{{sub.degree}} </td>
							<td>{{sub.author}} </td>
							<td>{{sub.relative_year}} </td>
							<td>{{sub.relative_semester}} </td>
							<td>{{sub.get_analysis_status_display}}</td>
							<td>{{sub.timestamp}}</td>
							<td class="table-primary bg-primary bg-white">
								<!-- <a href="{% url 'submission:SubmissionDetailView' sub.pk %}">Detalhes </a><br> -->
								<!-- <a href="{% url 'submission:SubmissionUpdateView' sub.pk %}">Editar </a><br> -->
								{% if sub.get_analysis_status_display != 'Executando' %}
									<a href="{% url 'submission:SubmissionDeleteView' sub.pk %}">Remover </a><br>
									<hr class="col-xs-12">
								{% endif %}
								{% if sub.get_analysis_status_display == 'Terminado' %}
									<a href="{% url 'degree:index' submission_id=sub.id %}"> Visualizar relatório (gráficos e taxas) </a>
									<br>
									<hr class="col-xs-12">
									<a href="{% url 'submission:download' submission_id=sub.id%}"> Baixar resultados </a>
								{% endif %}
							</td>

						</tr>
			  {% endfor %}
			</tbody>
		</table>
	</div>
</div>

{% endblock content %}


{% block js-foot %}
<script>
    $('#submission_table').dataTable({
		"bPaginate": true,
		"bInfo": false,
		"aaSorting": [[ 0, "desc" ]],
		"responsive": true,
		"createdRow": function( row, data, dataIndex ) {
			console.log(dataIndex);
			switch(data[5]){
				case "Falha":
					$(row).addClass('table-danger');
					break;
				case "Executando":
					$(row).addClass('table-warning');
					break;
				case "Terminado":
					// $(row).addClass('table-success');
					break;
			}
			$(data[7]).removeClass("table-danger");
			$(data[7]).removeClass("table-warning");
			$(data[7]).removeClass("table-success");
			$(data[7]).addClass("table-primary");

		}
	});


</script>
{% endblock js-foot %}